image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      mysql -u root -e "create database proedt_dev" &&
      mysql -u root -e "CREATE USER 'proedt'@'localhost' IDENTIFIED BY 'grq5efv.XFT.zbe8kxt';" &&
      mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'proedt'@'localhost';" &&
      mysql -u root -e "FLUSH PRIVILEGES;" &&
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      composer install
    command: >
      php -S 0.0.0.0:8080 -t public/
    